### ISSUE TITLE
Redirect URLs with invalid readable path segment

### ISSUE THREAD

**Issue by mbrodala** [pagemachine/typo3-flat-urls#19]
Another neat feature of Stack Overflow is the automatic redirect from invalid to correct URLs if at least the ID part is correct. An example:

- Correct: https://stackoverflow.com/questions/46450764/switch-to-composer-mode-in-running-instance/
- Invalid: https://stackoverflow.com/questions/46450764/test/
  ▶️ Redirects to https://stackoverflow.com/questions/46450764/switch-to-composer-mode-in-running-instance/

**Comment by ursbraem** [comment]
My thoughts on this:

* To resolve an URL, only the ID parts should be parsed. `https://example.org/de/415/nevermind/98/doesntmatter` (for a record on a page) or simply `https://example.org/de/415/nevermind` for a page
* For SEO, there has to be a 301 if the slugs used in the URL differ from what is saved as slug (e.g. because the link is older than the current slug). So after the routing has been done, check with the current slugs of the page and record that has been identified from the URL. If they don't match, add a 301 to the current full URL.

**Comment by mbrodala** [comment]
Not going to add this for now unless it is requested by popular demand and a PR is provided.

The overhead for such a nice-to-have feature is too high given that potentially *any* SO-like URL must be evaluated to ensure alternative paths are accepted.
